//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCFV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colisiones
    {
        public int idColision { get; set; }
        public int idConductor { get; set; }
        public int idVehiculo { get; set; }
        public System.DateTime fechaColision { get; set; }
        public string descripcion { get; set; }
        public byte[] sentenciaFirme { get; set; }
        public byte[] avisoAccidente { get; set; }
        public byte[] seguro { get; set; }
    
        public virtual Conductor Conductor { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
