//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCFV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conductor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conductor()
        {
            this.Colisiones = new HashSet<Colisiones>();
            this.Reparaciones = new HashSet<Reparaciones>();
            this.Solicitud = new HashSet<Solicitud>();
        }
    
        public int idConductor { get; set; }
        public int cedula { get; set; }
        public string nombreChofer { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string tipoLicencia { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public bool habilitado { get; set; }
        public string descripHabilitado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Colisiones> Colisiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reparaciones> Reparaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud> Solicitud { get; set; }
    }
}
