//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCFV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reparaciones
    {
        public int reparacionId { get; set; }
        public int tallerId { get; set; }
        public System.DateTime fecha { get; set; }
        public double costoTotal { get; set; }
        public string descripcion { get; set; }
        public double montoReserva { get; set; }
        public double kmInicial { get; set; }
        public double kmFinal { get; set; }
        public string numFactura { get; set; }
        public int idConductor { get; set; }
        public int idVehiculo { get; set; }
    
        public virtual Conductor Conductor { get; set; }
        public virtual Taller Taller { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
