//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCFV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int idSolicitud { get; set; }
        public int idUsuario { get; set; }
        public int idVehiculo { get; set; }
        public int idConductor { get; set; }
        public string nombreSolicitante { get; set; }
        public string nomDeparta { get; set; }
        public string destino { get; set; }
        public string justificacionSalida { get; set; }
        public System.DateTime fechaSolicitud { get; set; }
        public System.DateTime fechaSalida { get; set; }
        public System.DateTime fechaEntrada { get; set; }
        public int numConsecutivo { get; set; }
        public string funcionarioViaja { get; set; }
        public string observaciones { get; set; }
        public string estado { get; set; }
    
        public virtual Conductor Conductor { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
