//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCFV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Taller()
        {
            this.Reparaciones = new HashSet<Reparaciones>();
        }
    
        public int idTaller { get; set; }
        public string cedJuridica { get; set; }
        public string nombreTaller { get; set; }
        public string especialidad { get; set; }
        public string telefono { get; set; }
        public string ubicacion { get; set; }
        public string correo { get; set; }
        public string representante { get; set; }
        public bool habilitado { get; set; }
        public string descripHabilitado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reparaciones> Reparaciones { get; set; }
    }
}
