//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCFV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Colisiones = new HashSet<Colisiones>();
            this.Reparaciones = new HashSet<Reparaciones>();
            this.Solicitud = new HashSet<Solicitud>();
        }
    
        public int idVehiculo { get; set; }
        public string placa { get; set; }
        public string marca { get; set; }
        public string color { get; set; }
        public string tipoLlanta { get; set; }
        public string tipoChasis { get; set; }
        public string tipoMotor { get; set; }
        public string tipoVehiculo { get; set; }
        public string poliza { get; set; }
        public bool comprado { get; set; }
        public string numFactura { get; set; }
        public double costo { get; set; }
        public bool habilitado { get; set; }
        public string descripHabilitado { get; set; }
        public string donadoPor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Colisiones> Colisiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reparaciones> Reparaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud> Solicitud { get; set; }
    }
}
